name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Configurar identidad (evita errores de commit)
          git config --global user.email "paco.andres03@gmail.com"
          git config --global user.name "Oscar Andrés Sánchez"
          
          # 2. Preparar LFS y clonar el Space
          git lfs install
          git clone https://huggingface.co/spaces/escorpionfake/modelo-ia-recetas space
          
          # 3. Sincronizar archivos (excluyendo .git del repo original)
          rsync -av --exclude=".git" ./ space/
          
          # 4. Commit y Push al Space
          cd space
          git add .
          # Solo hacer commit si hay cambios reales
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Auto deploy: Actualización de S.I.R.I. desde GitHub"
            git push https://escorpionfake:$HF_TOKEN@huggingface.co/spaces/escorpionfake/modelo-ia-recetas main
          else
            echo "No hay cambios para desplegar."
          fi