name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true # Crucial para traer los archivos pesados desde GitHub

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Configurar identidad
          git config --global user.email "paco.andres03@gmail.com"
          git config --global user.name "Oscar Andrés Sánchez"
          
          # 2. Inicializar LFS
          git lfs install
          
          # 3. Clonar el Space
          git clone https://huggingface.co/spaces/escorpionfake/modelo-ia-recetas space
          
          # 4. Sincronizar archivos
          rsync -av --exclude=".git" ./ space/
          
          # 5. Forzar a que el Space reconozca el archivo como LFS
          cd space
          git lfs track "*.keras"
          git lfs track "*.h5"
          git add .gitattributes
          git add models/model_mobilenetv2.keras
          
          # 6. Commit y Push
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Auto deploy: Incluyendo modelo S.I.R.I. vía LFS"
            git push https://escorpionfake:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/escorpionfake/modelo-ia-recetas main --force
          else
            echo "Sin cambios"
          fi